# Generated by Django 3.1.5 on 2021-01-21 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('link', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.CharField(max_length=100, unique=True)),
                ('related_web_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.webaddress')),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alt', models.CharField(max_length=100, unique=True)),
                ('src', models.CharField(max_length=100, unique=True)),
                ('related_web_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.webaddress')),
            ],
        ),
    ]
