# Generated by Django 3.1.5 on 2021-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='alt',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='src',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='webaddress',
            name='link',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
