# Generated by Django 3.1.5 on 2021-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210121_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='alt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='src',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
