# Generated by Django 3.1.5 on 2021-01-22 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210122_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaddress',
            name='validity_term',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 33, 37, 703675)),
        ),
    ]
