# Generated by Django 3.1.5 on 2021-01-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_webaddress_validity_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webaddress',
            name='validity_term',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 17, 19, 0, 632141)),
        ),
    ]
