# Generated by Django 3.1.5 on 2021-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210123_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaddress',
            name='scraped_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webaddress',
            name='scraped_text',
            field=models.BooleanField(default=False),
        ),
    ]
