# Generated by Django 3.1.5 on 2021-01-23 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('link', models.CharField(max_length=2048, unique=True)),
                ('validity_term', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'data_webaddress',
            },
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.CharField(max_length=1000)),
                ('related_web_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap_app.webaddress')),
            ],
            options={
                'db_table': 'data_textdata',
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alt', models.CharField(max_length=1000)),
                ('src', models.CharField(max_length=2048)),
                ('related_web_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap_app.webaddress')),
            ],
            options={
                'db_table': 'data_imagedata',
            },
        ),
    ]
