# Generated by Django 3.1.5 on 2021-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webaddress',
            name='scraped_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webaddress',
            name='scraped_text',
            field=models.BooleanField(default=False),
        ),
    ]
